var ipas = {
"b": ["'b'uy", "ca'b'"],
"d": ["'d'ye", "ca'd'", "'d'o"],
"ð": ["'th'y", "brea'the'", "fa'th'er"],
"dʒ": ["'g'iant", "ba'dge'", "'j'am"],
"f": ["'f'an", "ca'ff'", "'ph'i"],
"g": ["'g'uy", "ba'g'"],
"ɡ": ["'g'uy", "ba'g'"],
"h": ["'h'igh", "a'h'ead"],
"j": ["'y'es", "hallelu'j'ah"],
"k": ["s'k'y", "'c'ra'ck'"],
"l": ["'l'ie", "s'l'y", "ga'l'"],
"m": ["'m'y", "s'm'ile", "ca'm'"],
"n": ["'n'igh", "s'n'ide", "ca'n'"],
"ŋ": ["sa'ng'", "si'n'k", "si'ng'er"],
"θ": ["'th'igh", "ma'th'"],
"p": ["'p'ie", "s'p'y", "ca'p'"],
"r": ["'r'ye", "t'r'y", "ve'r'y"],
"s": ["'s'igh", "ma'ss'"],
"ʃ": ["'sh'y", "ca'sh'", "emo'ti'on"],
"t": ["'t'ie", "s't'y", "ca't'", "a't'om"],
"tʃ": ["'ch'ina", "ca'tch'"],
"v": ["'v'ie", "ha've'"],
"w": ["'w'ye", "s'w'ine"],
"hw": ["'wh'y"],
"z": ["'z'oo", "ha's'"],
"ʒ": ["equa'ti'on", "plea's'ure", "vi'si'on", "bei'g'e"],
"x": ["u'gh'", "lo'ch'", "'Ch'anukah"],
"ʔ": ["uh'-'oh"],
"ɑː": ["p'a'lm", "f'a'ther", "br'a'"],
"ɑr": ["st'ar't", "b'ar'd", "b'ar'n", "sn'ar'l", "st'ar'"],
"ɒ": ["l'o't", "p'o'd", "J'o'hn"],
"ɒr": ["m'or'al", "f'or'age"],
"æ": ["tr'a'p", "p'a'd", "sh'a'll", "b'a'n "],
"ær": ["b'arr'ow", "m'arr'y"],
"aɪ": ["pr'i'ce", "r'i'de", "f'i'le", "f'i'ne", "p'ie'"],
"aɪər": ["'Ire'land", "h'ire'"],
"aɪ.ər": ["h'igher'", "b'uyer'"],
"aʊ": ["m'ou'th", "l'ou'd", "f'ou'l", "d'ow'n", "h'ow'"],
"aʊər": ["fl'our'"],
"aʊ.ər": ["fl'ower'"],
"ɛ": ["dr'e'ss", "b'e't", "f'e'll", "m'e'n"],
"ɛr": ["'err'or", "m'err'y"],
"eɪ": ["f'a'ce", "m'a'de", "f'ai'l", "v'ei'n", "p'ay'"],
"ɛər": ["squ'are'", "m'are'", "sc'ar'ce", "c'air'n", "M'ar'y"],
"eɪ.ər": ["m'ayor'"],
"ɪ": ["k'i't", "l'i'd", "f'i'll", "b'i'n"],
"ɪr": ["m'irr'or", "S'ir'ius"],
"iː": ["fl'ee'ce", "s'ee'd", "f'ee'l", "m'ea'n", "s'ea'"],
"ɪər": ["n'ear'", "b'ear'd", "f'ier'ce", "s'er'ious"],
"iː.ər": ["fr'eer'"],
"ɔː": ["th'ough't", "M'au'd", "d'aw'n", "f'a'll", "str'aw'"],
"ɔr": ["n'or'th", "b'or'n", "w'ar'", "L'aur'a"],
"ɔː.ər": [" s'awer'"],
"ɔɪ": ["ch'oi'ce", "v'oi'd", "f'oi'l", "c'oi'n", "b'oy'"],
"ɔɪər": ["l'oir']]"],
"ɔɪ.ər": ["l'awyer'"],
"oʊ": ["g'oa't", "c'o'de", "f'oa'l", "b'o'ne", "g'o'"],
"ɔər": ["f'or'ce", "m'ore'", "b'oar'", "'or'al"],
"oʊ.ər": ["m'ower'"],
"ʊ": ["f'oo't", "g'oo'd", "f'u'll", "w'o'man"],
"ʊr": ["c'our'ier"],
"uː": ["g'oo'se", "f'oo'd", "f'oo'l", "s'oo'n", "ch'ew'", "d'o'"],
"ʊər": ["b'oor'", "m'oor'", "t'our'ist"],
"uː.ər": ["tr'uer'"],
"juː": ["c'ue'd", "c'u'te", "m'u'le", "t'u'ne", "q'ueue'", "'you'"],
"jʊər": ["c'ure'"],
"juː.ər": ["f'ewer'"],
"ʌ": ["str'u't", "m'u'd", "d'u'll", "g'u'n"],
"ʌr": ["b'or'ough", "h'urr'y"],
"ɜr": ["n'ur'se", "w'or'd", "g'ir'l", "f'er'n", "f'urr'y "],
"ə": ["Ros'a'’s", "'a' mission", "qui'e't", "foc'u's"],
"ər": ["lett'er'", "p'er'ceive "],
"ɨ": ["ros'e's", "'e'mission"],
"ən": ["butt'on'"],
"ɵ": ["'o'mission"],
"əm": ["rhyth'm'"],
"ʉ": ["beautif'u'l", "curric'u'lum"],
"əl": ["bott'le'"],
"i": ["happ'y'", "ser'i'ous"],
"ᵊ": ["(vowel is frequently dropped: nasturt'i'um)"],
"ⁱ": ["(vowel is frequently dropped: nasturt'i'um)"],
"ˈ": ['Stress'],
".": ['Syllabification'],
"ˌ": ['Stress']
}
